# Generated by Django 5.2.2 on 2025-06-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brands_alter_car_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
