# Generated by Django 5.2.2 on 2025-07-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='cars_value',
            new_name='cars_price',
        ),
    ]
