# Generated by Django 5.2.2 on 2025-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
